markdown: rdiscount
highlighter: pygments
domain: 'https://lab.okfn.de/jedeschule'
staticurl: /assets/
exclude:
  - "CNAME"
  - "LICENSE"
  - "browserlist"
  - "Gemfile*"
  - "Readme.md"
  - "*.sh"
  - ".idea/"
  - ".git/"
  - "local/"
  - "scripts/"
  - "_site/"
  - "vendor/"
  - "assets/vendor/leaflet/docs/"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - octopress-autoprefixer
sass:
  sass_dir: assets/style/_scss
  style: compressed
collections:
  laender:
    output: true
    permalink: laender/:path/
settings:
  debug: false