markdown: rdiscount
highlighter: pygments
domain: 'https://jedeschule.de'
staticurl: /assets/
exclude:
  - "CNAME"
  - "LICENSE"
  - "browserlist"
  - "Gemfile*"
  - "Readme.md"
  - "*.sh"
  - ".sass-cache/"
  - ".idea/"
  - ".git/"
  - "local/"
  - "scripts/"
  - "_site/"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - octopress-autoprefixer
sass:
  sass_dir: assets/style/_scss
  style: compressed
collections:
  laender:
    output: true
    permalink: laender/:path/
  projects:
    output: false
settings:
  debug: false